name = "ion"

[install]
completion=true
export_path=true
quiet=false
compile="min"
optimize=2

[sysimg]
path="deps/lib"
incremental=true
filter_stdlibs=false
cpu_target="x86-64"

[download]
host="github.com"
user="Roger-luo"
repo="IonCLI.jl"
