on:
    push:
      # Sequence of patterns matched against refs/tags
      tags:
        - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  
jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
            - os: ubuntu-latest
              julia-version: '1.4.2'
              asset_name: ion-1.4.2-linux-x86_64.tar.gz
            - os: ubuntu-latest
              julia-version: '1.5.0-rc1'
              asset_name: ion-1.5.0-rc1.0-linux-x86_64.tar.gz
            - os: macOS-latest
              julia-version: '1.4.2'
              asset_name: ion-1.4.2-darwin-x86_64.tar.gz
            - os: macOS-latest
              julia-version: '1.5.0-rc1'
              asset_name: ion-1.5.0-rc1.0-darwin-x86_64.tar.gz

    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Build project # This would actually build your project, using zip for an example artifact
      uses: julia-actions/setup-julia@v1
      with:
        version: ${{ matrix.julia-version }}
    - run: julia --project -e "using Pkg; Pkg.instantiate()"
    - run: julia --project -e "using Pkg; Pkg.status()"
    - run: |
        julia --project deps/build.jl sysimg
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./deps/${{ matrix.asset_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
        overwrite: true
